### ISSUE TITLE
Refactor Tree + Error handling wrt 0-padded column leaves

### ISSUE THREAD

**Issue by jleni** [Zondax/neptune#1]
Depends on https://github.com/filecoin-project/neptune/pull/89 getting merged

**Comment by jleni** [comment]
The related PR has been issued again under another number https://github.com/filecoin-project/neptune/pull/93

**Comment by jleni** [comment]
It seems that there is a minor merge conflict and the related PR is ready to go
https://github.com/filecoin-project/neptune/pull/93

**Comment by jleni** [comment]
@neithanmo is this soemthing we can close?

**Comment by neithanmo** [comment]
yes, i will do.
